### ISSUE TITLE
About source code of your paper "HEMP: High-order Entropy Minimization for neural network comPression"

### ISSUE THREAD

**Issue by OctoberKat** [EIDOSlab/LOBSTER#1]
Hi, I have read your paper _HEMP: High-order Entropy Minimization for neural network comPression_, which is very attractive and enlightening. In your paper, it says the source code will be made available on Github but I did not find it by keyword HEMP. If you have released the source code, could you please send me a URL? I would highly appreciate it! Can't wait to use HEMP on my NN models:)

**Comment by AndreaBrg** [comment]
@enzotarta

**Comment by OctoberKat** [comment]
Oh, I find it! Here, https://github.com/enzotarta/HEMP. Thank you very much and have a good day!
